### ISSUE TITLE
Support for Aero 15 WB (2020)

### ISSUE THREAD

**Issue by Androidjent** [blmhemu/opengigabyte#1]
**Prechecks**
Is your device in the list of supported devices ? - No

**Provide**
* Device Name :  Gigabyte Aero 15 WB from 2020
* lsusb : Output of `lsusb` (Ex: Bus 001 Device 005: ID 1044:7a39 Chu Yuen Enterprise Co., Ltd USB-HID Keyboard)
Bus 001 Device 005: ID 1044:7a3b Chu Yuen Enterprise Co., Ltd USB-HID Keyboard

Available devices:
/dev/hidraw0:	GIGABYTE USB-HID Keyboard
/dev/hidraw1:	GIGABYTE USB-HID Keyboard
/dev/hidraw2:	GIGABYTE USB-HID Keyboard
/dev/hidraw3:	GIGABYTE USB-HID Keyboard
Select the device event number [0-3]: 2
D: 0
R: 253 05 01 09 02 a1 01 85 01 09 01 a1 00 05 09 15 00 25 01 19 01 29 05 75 01 95 05 81 02 95 03 81 01 05 01 16 01 80 26 ff 7f 09 30 09 31 75 10 95 02 81 06 15 81 25 7f 09 38 75 08 95 01 81 06 05 0c 0a 38 02 95 01 81 06 c0 c0 05 01 09 80 a1 01 85 02 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05 81 01 c0 05 0c 09 01 a1 01 85 03 19 00 2a ff 07 15 00 26 ff 07 95 01 75 10 81 00 c0 06 02 ff 09 01 a1 01 85 04 15 00 26 ff 00 09 03 75 08 95 03 81 00 c0 05 01 09 06 a1 01 85 05 05 07 95 01 75 08 81 03 95 e8 75 01 15 00 25 01 05 07 19 00 29 e7 81 00 c0 05 01 09 02 a1 01 85 06 15 00 26 ff 7f 09 30 09 31 75 10 95 02 81 02 c0 06 89 ff 09 10 a1 01 85 5a 09 01 15 00 26 ff 00 75 08 95 10 b1 00 c0 05 01 09 0c a1 01 85 07 15 00 25 01 09 c6 95 01 75 01 81 06 75 07 81 03 c0
N: GIGABYTE USB-HID Keyboard
P: usb-0000:00:14.0-11/input2
I: 3 1044 7a3b

FN-ESC: (fan speed)
D: 0
E: 0.000001 4 04 00 00 84

FN-F1:  (Zz)
E: 14.447944 2 02 02
E: 14.487908 2 02 00

FN-F2: (Wifi signal bars)
E: 48.719909 4 04 00 00 7c

FN-F3: (Brightness down)
E: 65.159900 4 04 00 00 7d

FN-F4: (Brightness up)
E: 81.063780 4 04 00 00 7e

FN-F5: (LCD)
p

FN-F6: (Disable monitor (rectangle with x inside))
E: 153.679820 4 04 00 00 80

FN-F7: (Mute - works)
E: 173.007795 3 03 e2 00
E: 173.015694 4 04 00 01 85
E: 173.095768 3 03 00 00
E: 173.103739 4 04 00 00 85

FN-F8: (Sound down - works)
E: 190.031725 3 03 ea 00
E: 190.039711 4 04 00 01 86
E: 190.103753 3 03 00 00
E: 190.111719 4 04 00 00 86

FN-F9: (Sound up - works)
E: 207.999748 3 03 e9 00
E: 208.007616 4 04 00 01 87
E: 208.087791 3 03 00 00
E: 208.095720 4 04 00 00 87

FN-F10: (Disable touchpad)
E: 235.735868 4 04 00 00 81

FN-F11: (Aeroplane mode - works)
E: 259.495646 2 07 01

FN-F12: (no function)
No output

The FN-F5 option opens the display configuration dialog in xfce and when I run hid-recorder on another tty it just shows a p

**Comment by blmhemu** [comment]
Are the brightness keys working ?

**Comment by blmhemu** [comment]
Closing as no reply.
