### ISSUE TITLE
Installation on Fedora

### ISSUE THREAD

**Issue by SIMULATAN** [blmhemu/opengigabyte#10]
The Makefile states that you are supposed to install the driver using the distribution package, but there is none on fedora. What is the suggested way of installing it? I'd be fine with maintaining the fedora package, if needed, but please bear in mind that I don't quite have prior knowledge in this area (I'd be down to learn it tho).

I'm using an Aorus 15P KD, which I can also submit an issue for, but I first wanted to try and see if the existing code already works.

**Comment by SIMULATAN** [comment]
I've updated my local code to include the right vendor and keyboard ID, but I still don't know what makefile scripts to run and in what order. I'd appreciate help!

**Comment by blmhemu** [comment]
Hey ! The driver is not yet packaged for fedora (appreciate any help though). But if you link to test it out, then, you can run `make` in the driver directory and `insmod` the resultant module.
