### ISSUE TITLE
Gigabyte Aero 15X V8

### ISSUE THREAD

**Issue by LorenzoMinutolo** [blmhemu/opengigabyte#2]
**Prechecks**
Is your device in the list of supported devices ? - [Yes]

**Provide**
* Device Name : Gigabyte Aero 15X V8
* lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 002: ID 0bda:5442 Realtek Semiconductor Corp. Cable Matters USB-C Video Cable
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 0bda:0328 Realtek Semiconductor Corp. USB3.0-CRW
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 13d3:56a2 IMC Networks USB2.0 HD UVC WebCam
Bus 001 Device 003: ID 04f3:0c11 Elan Microelectronics Corp. ELAN:Fingerprint
Bus 001 Device 002: ID 045e:07b2 Microsoft Corp. 2.4GHz Transceiver v8.0 used by mouse Wireless Desktop 900
Bus 001 Device 006: ID 1044:7a3f Chu Yuen Enterprise Co., Ltd USB-HID Keyboard
Bus 001 Device 005: ID 8087:0029 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Next Steps**
Fn+ESC command:
Available devices:
/dev/hidraw0:	Microsoft Microsoft® 2.4GHz Transceiver v7.0
/dev/hidraw1:	Microsoft Microsoft® 2.4GHz Transceiver v7.0
/dev/hidraw2:	Microsoft Microsoft® 2.4GHz Transceiver v7.0
/dev/hidraw3:	GIGABYTE USB-HID Keyboard
/dev/hidraw4:	GIGABYTE USB-HID Keyboard
/dev/hidraw5:	GIGABYTE USB-HID Keyboard
/dev/hidraw6:	GIGABYTE USB-HID Keyboard
/dev/hidraw7:	MX Master 2S
Select the device event number [0-7]: 3
D: 0
R: 75 05 01 09 06 a1 01 05 08 15 00 25 01 19 01 29 03 75 01 95 03 91 02 95 05 91 01 05 07 19 e0 29 e7 75 01 95 08 81 02 95 08 81 01 15 00 26 ff 00 19 00 2a ff 00 75 08 95 06 81 00 05 07 19 00 29 df 15 00 25 01 75 01 95 e0 81 02 c0
N: GIGABYTE USB-HID Keyboard
P: usb-0000:00:14.0-11/input0
I: 3 1044 7a3f
D: 0
E: 0.000000 36 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Fn + lum up/dw (same output for both)
E: 49.512459 36 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Additional context**
Luminosity does not work.
Great release! keep up the good stuff!

**Comment by blmhemu** [comment]
This looks a bit different. Can you post the result of all Fn+* keys ? Like in https://github.com/blmhemu/opengigabyte/issues/1#issue-733498309

**Comment by LorenzoMinutolo** [comment]
After retrying with a different hid device (since the codes out of
/dev/hidraw3: GIGABYTE USB-HID Keyboard were all the same) I got this:

Available devices:
/dev/hidraw0: Microsoft Microsoft® 2.4GHz Transceiver v7.0
/dev/hidraw1: Microsoft Microsoft® 2.4GHz Transceiver v7.0
/dev/hidraw2: Microsoft Microsoft® 2.4GHz Transceiver v7.0
/dev/hidraw3: GIGABYTE USB-HID Keyboard
/dev/hidraw4: GIGABYTE USB-HID Keyboard
/dev/hidraw5: GIGABYTE USB-HID Keyboard
/dev/hidraw6: GIGABYTE USB-HID Keyboard
/dev/hidraw7: MX Master 2S
Select the device event number [0-7]: 5
D: 0
R: 253 05 01 09 02 a1 01 85 01 09 01 a1 00 05 09 15 00 25 01 19 01 29 05 75
01 95 05 81 02 95 03 81 01 05 01 16 01 80 26 ff 7f 09 30 09 31 75 10 95 02
81 06 15 81 25 7f 09 38 75 08 95 01 81 06 05 0c 0a 38 02 95 01 81 06 c0 c0
05 01 09 80 a1 01 85 02 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05 81
01 c0 05 0c 09 01 a1 01 85 03 19 00 2a ff 07 15 00 26 ff 07 95 01 75 10 81
00 c0 06 02 ff 09 01 a1 01 85 04 15 00 26 ff 00 09 03 75 08 95 03 81 00 c0
05 01 09 06 a1 01 85 05 05 07 95 01 75 08 81 03 95 e8 75 01 15 00 25 01 05
07 19 00 29 e7 81 00 c0 05 01 09 02 a1 01 85 06 15 00 26 ff 7f 09 30 09 31
75 10 95 02 81 02 c0 06 89 ff 09 10 a1 01 85 5a 09 01 15 00 26 ff 00 75 08
95 10 b1 00 c0 05 01 09 0c a1 01 85 07 15 00 25 01 09 c6 95 01 75 01 81 06
75 07 81 03 c0
N: GIGABYTE USB-HID Keyboard
P: usb-0000:00:14.0-11/input2
I: 3 1044 7a3f

ESC: E: 0.000007 4 03 00 00 7d - no effect
F1: Can't enable sleep mode right now. That works!
F2: E: 151.233450 4 04 00 00 7c - wifi on/off, not working

F3:
E: 186.681847 4 03 70 00 7d
E: 186.681859 4 03 00 00 7d
-lum down- not working

F4:
E: 226.194244 4 03 6f 00 7e
E: 226.194256 4 03 00 00 7e
-lum up- not working

F5: works, no code response

F6: E: 318.363127 4 04 00 00 80 -keypad off- not working

F7:
E: 346.115404 3 03 e2 00
E: 346.123319 4 04 00 01 85
E: 346.283338 3 03 00 00
E: 346.291433 4 04 00 00 85
mute - working

F8:
E: 373.539712 3 03 ea 00
E: 373.547630 4 04 00 01 86
E: 373.699722 3 03 00 00
E: 373.707691 4 04 00 00 86
volume down - working

F9:
E: 398.139964 3 03 e9 00
E: 398.147868 4 04 00 01 87
E: 398.291958 3 03 00 00
E: 398.299868 4 04 00 00 87
volume up - working

F10:
E: 436.548409 4 04 00 00 81
- no idea, nor effects -

F11:
E: 474.908705 2 07 01
airplane mode - working

F12: no fn key







Il giorno gio 3 dic 2020 alle ore 23:46 Hemanth Bollamreddi <
notifications@github.com> ha scritto:

**Comment by blmhemu** [comment]
Hey ! i think the problem is not the driver. The key codes look fine. My guess is that you did not map your keys to change the brightness. Try installing xbacklight or light utility (https://github.com/blmhemu/opengigabyte#notes)

**Comment by blmhemu** [comment]
Closing as stale issue.
