### ISSUE TITLE
I'd like to be the maintainer of the AUR package

### ISSUE THREAD

**Issue by rcassani** [blmhemu/opengigabyte#6]
Thanks for the driver. Now I can use the brightness keys in the AORUS15G. I added the keyboard model and required changes in this [PR](https://github.com/blmhemu/opengigabyte/pull/5). I noticed that a previous version of driver exists as an AUR package with the name [openaero](https://aur.archlinux.org/pkgbase/openaero/). 

I'd like to maintain the **opengigabyte** repo as an AUR package for Arch. However, going through the previous package, I don't get why there are: [openaero-meta](https://aur.archlinux.org/packages/openaero-meta/) and [openaero-driver-dmks](https://aur.archlinux.org/packages/openaero-driver-dkms/). Could you tell me why there are two packages with the same PKGBUILD?

**Comment by blmhemu** [comment]
Hello! It was due to the package structure of [openrazor](https://openrazer.github.io/). I don't think it is needed.

**Comment by blmhemu** [comment]
Sure! Please merge any scripts needed to make the AUR package and feel free to maintain the same.
