### ISSUE TITLE
Support for [AORUS 17G YC]

### ISSUE THREAD

**Issue by morialo3** [blmhemu/opengigabyte#9]
**Prechecks**
Is your device in the list of supported devices ? - [No]

**Provide**
* Device Name :  (Gigabyte Aorus 17G YC - RTX 30 series)
* lsusb :  (Bus 001 Device 003: ID 1044:7a3c Chu Yuen Enterprise Co., Ltd Fusion RGB KB)

"sudo hid-recorder"

Available devices:
/dev/hidraw0:   GIGABYTE Fusion RGB KB
/dev/hidraw1:   GIGABYTE Fusion RGB KB
/dev/hidraw2:   GIGABYTE Fusion RGB KB
Select the device event number [0-2]: 0
D: 0
R: 65 05 01 09 06 a1 01 05 07 19 e0 29 e7 15 00 25 01 75 01 95 08 81 02 75 08 95 01 81 01 05 08 75 01 95 05 19 01 29 05 91 02 75 03 95 01 91 01 05 07 19 00 2a ff 00 15 00 26 ff 00 75 08 95 06 81 00 c0
N: GIGABYTE Fusion RGB KB
P: usb-0000:00:14.0-11/input0
I: 3 1044 7a3c
D: 0
(Fn+F10)
E: 0.000000 8 09 00 73 00 00 00 00 00
E: 0.180940 8 00 00 00 00 00 00 00 00

Select the device event number [0-2]: 1
D: 0
R: 79 05 01 09 06 a1 01 05 07 19 e0 29 e7 15 00 25 01 75 01 95 08 81 02 19 00 29 67 15 00 25 01 75 01 95 68 81 02 19 87 29 8b 09 90 09 91 15 00 25 01 75 01 95 07 81 02 75 01 95 01 81 01 05 08 75 01 95 05 19 01 29 05 91 02 75 03 95 01 91 01 c0
N: GIGABYTE Fusion RGB KB
P: usb-0000:00:14.0-11/input1
I: 3 1044 7a3c
D: 0
(Fn+F1)
E: 0.000000 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 51.743016 15 00 00 00 00 00 00 00 00 00 00 00 00 80 00 00
E: 51.960062 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 52.473067 15 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00
E: 52.626066 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 52.666090 15 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00
E: 52.803120 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 53.316098 15 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00
E: 53.412093 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 53.557161 15 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00
E: 53.669099 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 53.910092 15 00 00 00 00 00 00 00 00 00 00 00 00 08 00 00
E: 54.022089 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 54.207098 15 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00
E: 54.303067 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
(Fn+F5)
E: 178.979167 15 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 179.015145 15 08 00 00 08 00 00 00 00 00 00 00 00 00 00 00
E: 179.119069 15 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E: 179.156145 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Select the device event number [0-2]: 2
D: 0
R: 282 05 01 09 02 a1 01 85 01 09 01 a1 00 05 09 19 01 29 05 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 01 05 01 09 30 09 31 16 01 80 26 ff 7f 75 10 95 02 81 06 09 38 15 81 25 7f 75 08 95 01 81 06 05 0c 0a 38 02 95 01 81 06 c0 c0 05 01 09 80 a1 01 85 02 19 81 29 83 15 00 25 01 75 01 95 03 81 02 75 05 95 01 81 01 c0 06 02 ff 09 01 a1 01 85 04 15 00 26 ff 00 09 03 75 08 95 03 81 00 c0 05 0c 09 01 a1 01 85 03 19 00 2a ff 02 15 00 26 ff 7f 75 10 95 03 81 00 75 08 95 01 81 01 c0 06 00 ff 09 01 a1 01 85 06 15 00 26 ff 00 09 30 95 03 75 08 81 02 c0 06 01 ff 09 01 a1 01 85 07 15 00 26 ff 00 09 20 75 08 96 07 01 b1 02 c0 06 00 ff 0a 00 ff a1 01 85 09 15 00 26 ff 00 09 30 75 08 95 08 81 02 09 31 91 02 c0 05 01 09 0c a1 01 85 0a 15 00 25 01 09 c6 95 01 75 01 81 06 75 07 81 03 c0 05 01 09 02 a1 01 85 05 15 00 26 ff 7f 09 30 09 31 75 10 95 02 81 02 c0
N: GIGABYTE Fusion RGB KB
P: usb-0000:00:14.0-11/input2
I: 3 1044 7a3c
D: 0
(Fn+ESC)
E: 0.000000 4 04 00 00 84
E: 0.121001 4 04 00 00 00
(Fn+F1)
E: 71.651074 8 02 82 00 00 00 00 00 00
E: 71.772000 8 02 00 00 00 00 00 00 00
(Fn+F2)
E: 138.077583 4 04 00 00 7c
E: 138.182615 4 04 00 00 00
(Fn+F3)
E: 192.802585 4 04 00 00 7d
E: 192.930584 4 04 00 00 00
(Fn+F4)
E: 249.556618 4 04 00 00 7e
E: 249.701620 4 04 00 00 00
(Fn+F6)
E: 324.068654 4 04 00 00 80
E: 324.189704 4 04 00 00 00
(Fn+F7)
E: 409.576750 8 03 e2 00 00 00 00 00 00
E: 409.584532 4 04 00 01 85
E: 409.745655 8 03 00 00 00 00 00 00 00
E: 409.753672 4 04 00 00 85
(Fn+F8)
E: 453.663725 8 03 ea 00 00 00 00 00 00
E: 453.671560 4 04 00 01 86
E: 453.815728 8 03 00 00 00 00 00 00 00
E: 453.823736 4 04 00 00 86
(Fn+F9)
E: 501.715755 8 03 e9 00 00 00 00 00 00
E: 501.723584 4 04 00 01 87
E: 501.899692 8 03 00 00 00 00 00 00 00
E: 501.907745 4 04 00 00 87
(Fn+F10)
E: 544.446747 4 04 00 00 81
E: 544.454733 4 04 00 00 00
(Fn+F11)
E: 575.687788 2 0a c6

Note: since (Fn+F1) combination is a the shortcut for sleep mode, I think in the "device event number: 1" is not correct, and it might've recorded other inputs, since I had to wake the device from sleep.

**Comment by blmhemu** [comment]
I think this should already work on your device judging from the vendor id. Can u try installing and checking the same ?

**Comment by morialo3** [comment]
Working perfectly no issues so far, thanks alot.
